# Generated by Django 3.1.5 on 2021-04-01 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='isReported',
        ),
    ]
