# Generated by Django 3.1.5 on 2021-04-05 19:06

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0002_auto_20210405_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Sports'), (2, 'Music'), (3, 'Movies'), (4, 'Cooking'), (5, 'Reading'), (0, '')], max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.webp', null=True, upload_to='images'),
        ),
    ]
