# Generated by Django 3.1.5 on 2021-04-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0002_remove_profile_isreported'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isReported',
            field=models.BooleanField(default=False),
        ),
    ]
