# Generated by Django 3.1.5 on 2021-04-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0003_auto_20210405_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isReported',
            field=models.BooleanField(default=False),
        ),
    ]
