# Generated by Django 3.1.5 on 2021-04-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0005_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
