# Generated by Django 3.1.7 on 2021-03-25 23:34

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0006_auto_20210324_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'Item title 1.1'), ('item_key2', 'Item title 1.2'), ('item_key3', 'Item title 1.3'), ('item_key4', 'Item title 1.4'), ('item_key5', 'Item title 1.5')], max_length=49, null=True),
        ),
    ]
