# Generated by Django 3.1.5 on 2021-04-07 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0006_report_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
    ]
