# Generated by Django 3.1.5 on 2021-03-31 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0007_profile_interests'),
        ('social_app', '0007_auto_20210329_1533'),
    ]

    operations = [
    ]
