# Generated by Django 3.1.5 on 2021-03-31 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0008_merge_20210331_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='isReported',
        ),
    ]
