# Generated by Django 3.1.5 on 2021-04-12 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0008_report_username'),
        ('social_app', '0004_message'),
    ]

    operations = [
    ]
