# Generated by Django 3.1.5 on 2021-04-12 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0009_merge_20210412_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
