# Generated by Django 3.1.5 on 2021-03-31 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0009_remove_profile_isreported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
