# Generated by Django 3.1.7 on 2021-04-14 08:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_app', '0010_auto_20210412_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(related_name='f', to=settings.AUTH_USER_MODEL),
        ),
    ]
