# Generated by Django 3.1.5 on 2021-04-01 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0011_auto_20210331_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isReported',
            field=models.BooleanField(default=False),
        ),
    ]
