# Generated by Django 3.1.5 on 2021-04-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0012_friend_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='isread',
            field=models.BooleanField(default=False),
        ),
    ]
