# Generated by Django 3.1.5 on 2021-04-01 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0012_profile_isreported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='def.jpg', upload_to='images'),
        ),
    ]
