# Generated by Django 3.1.5 on 2021-04-01 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0014_auto_20210401_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='def.jpg', null=True, upload_to='images'),
        ),
    ]
