# Generated by Django 3.1.5 on 2021-04-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0015_auto_20210401_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
